#!/usr/bin/env bash
#sed -i "s/Listen 80/Listen ${PORT}/g" /etc/apache2/ports.conf
#sed -i "s/80/${PORT}/g" /etc/apache2/sites-enabled/*
sed -i 's/80/${PORT}/g' /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf
apache2-foreground